### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by BTruer** [sobriquette/pinclone#1]
Hello,

I would like to contribute or at least run this django app locally. What are the steps needed to do so. Could you please add it to the readme? 

Thank you,
Bhargav

**Comment by sobriquette** [comment]
Hey Bhargav!

It's exciting that you want to contribute, but this is actually a project I'm
doing as a take home test, so I need to all the work to be 100% me.

Feel free to run it locally though. I'll find some time this coming week to
add the steps to run the Django app into the README. What are you looking
to do with this project?

Also not sure if you're aware, but this is Melody -- we met through Dan and
Akhil. Hi!

- Melody

**Comment by BTruer** [comment]
Hi Melody,

Yes I saw your github and liked the repos on it. I just want to run this Django app locally to learn from it and see how the code matches with what you see when you run it. No worries about the time.

Thank you,
Bhargav

**Comment by sobriquette** [comment]
Updated the README to include setup and installation instructions.

**Comment by BTruer** [comment]
Got it thank you!
